### ISSUE TITLE
Compiler issues: git submodule

### ISSUE THREAD

**Issue by pneerincx** [SURFscz/pam-weblogin#16]
When using the source codes from a release/tag. E.g. the `*.tar.gz` available from https://github.com/SURFscz/pam-weblogin/releases/tag/v0.1 the `make` command will fail with
```
git submodule init
fatal: Not a git repository (or any of the parent directories): .git
make: *** [json-parser/configure] Error 128
```
because the `[json-parser @ 531a490](https://github.com/json-parser/json-parser/tree/531a49062975d6d2cd5d69b75ad5481a8c0e18c5)` subdir is empty: git submodules are not included in the source of releases.

If it would work, then the `git submodule update` will update the json parser to whatever is the latest and greatest unreleased version of that code on the day you compile it. Without version pinning of this dependency the reproducibility of the build can get problematic.

**Comment by baszoetekouw** [comment]
Unfortunately, this behaviour can apparently not be adjusted: the "Source code" zip and tar.gz files are created automatically by Github and includes neither the submodule code nor the git config to be able to pull them in manually (see https://github.com/dear-github/dear-github/issues/214).

As a workaround, we're now producing an extra source tarbal including the submodule for each release.  Hopefully that fixes your problem until github gets around to fix this.
