### ISSUE TITLE
Unfriendly error for pam-weblogin when user not found

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#20]
I was trying pam-weblogin, and got this error:
```
worker@sandbox:~/work/src$ make test
pamtester weblogin "${USERNAME:-unspecified}" authenticate
Server error!
pamtester: System error
make: *** [Makefile:82: test] Error 1
```
This seems to imply that something is wrong at the server or the server cannot be reached or something like that.  However, the actual issue was this:

```
SBS: 2022-08-04 13:23:54,929 base ERROR user: Service token Pam-weblogin Test, <Response 65 bytes [500 INTERNAL SERVER ERROR]>
Traceback (most recent call last):
  File "/opt/sbs/sbs/server/api/base.py", line 130, in wrapper
    body, status = f(*args, **kwargs)
  File "/opt/sbs/sbs/server/api/pam_websso.py", line 78, in start
    raise NotFound(f"User {filters} not found")
werkzeug.exceptions.NotFound: 404 Not Found: User {'uid': 'unspecified'} not found
```

Could we produce a clearer error message in this case?

**Comment by mrvanes** [comment]
I would advise against this, since it facilitates limitless guessing of existing user names.

**Comment by mrvanes** [comment]
Als SBS een 500 (of 404?) blijft retourneren is het aan de pam-weblogin kant lastig om onderscheid te maken tussen een server error of authentication error (in de huidige API call codeflow).

**Comment by baszoetekouw** [comment]
Idd, SBS moet de 404 netjes afhandelen.

**Comment by oharsta** [comment]
See also https://github.com/SURFscz/SBS/issues/274

**Comment by mrvanes** [comment]
Suggestion: https://github.com/SURFscz/pam-weblogin/tree/feature-server-error
This commit returns the server message on requests that have error set to True. This way we can control (in SBS) what the user gets to see depending on the error scenario.
```
$ sudo pamtester weblogin admin@scz-vm.ne authenticate
NotFound: https://sbs.scz-vm.net/pam-weblogin/start. IP: 172.20.1.24. User {'email': 'admin@scz-vm.ne'} not found
pamtester: Authentication failure
```

**Comment by baszoetekouw** [comment]
Nav f2f discussie: we gaan het volgende doen:
 - pam-weblogin logt de hele error messgae in de service logs
 - pam-weblogin aat aan de gebruiker alleen zien:
   - voor 4xx errors: "Permission denied"
   - voor 5xx: "Server error"

**Comment by baszoetekouw** [comment]
Dit is gereleased in v18/pam-weblogin-1.0
