### ISSUE TITLE
User with set password can always login with the default configuration

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#22]
With the pam config as specified in README, a user who has a working password is always able to log in, even when he enters te wrong pin or pam-weblogin fails in some other way.

I assume the pam config should be adjusted a bit more; simply adding `sufficient pam-weblogin` isn't enough.

**Comment by HarryKodden** [comment]
Solution is to specify:

`auth [success=done ignore=ignore default=die] pam_weblogin.so` /etc/pam-weblogin.conf`

**Comment by baszoetekouw** [comment]
@HarryKodden Kun je dit in de documentatie toevoegen/aanpassen?
