### ISSUE TITLE
pam-weblogin leest configfile niet?

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#23]
> if a configuration file is specified via an argument to the pam-weblogin module, the programme reads the executable's name (argv[0]) rather than the configuration file (argv[1]):
> ```
> if (!(cfg = getConfig((argc > 0) ? argv[0] : DEFAULT_CONF_FILE)))
> ```
> I believe it should be argv[1] and not argv[0]. Hope that helps. :)

Wel curieus, want ik dacht da dit gewoon werkte?

**Comment by mrvanes** [comment]
Ik snap ook niet waarom, maar het werkt als een dolle:
```
Aug 18 09:39:23 weblogin web-login[856]: Start of pam_weblogin
Aug 18 09:39:23 weblogin web-login[856]: argv[0]: /opt/pam-weblogin/pam-weblogin.conf
Aug 18 09:39:23 weblogin web-login[856]: argv[1]: (null)
```

**Comment by baszoetekouw** [comment]
Gedraagt ARGV[] zich misschien anders in pam?
