### ISSUE TITLE
pam-webllogin should check permissions of config file

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#24]
Before reading the config file, pam-weblogin should check that its permissions are secure, i.e., mode 0600 (or less) and owned by root.

This is mainly to make sure that the token in there is not accidentally exposed.

**Comment by mrvanes** [comment]
https://github.com/SURFscz/pam-weblogin/commit/0cf755a14c66e36d3e57ee29b33605eb8cb0ccbd

**Comment by baszoetekouw** [comment]
En verbeterd in https://github.com/SURFscz/pam-weblogin/commit/0aaff626df4176d9994c23d20f91389bcadf9e8b
