### ISSUE TITLE
documentatie van de config file verbeteren

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#28]
- hoe pam te configureren (met fallback https://linux.die.net/man/8/pam_succeed_if)
- welke opties kunnen er in de config file
- wat moeten de owner en permissies van de config file zijn

**Comment by baszoetekouw** [comment]
pam voorbeeld (logins vanaf ipranges in `exclude_iprange.conf` enuser in `admin` group hoeven niet door pam_weblogin, en alleen gebruikers met uid in aangegeven range):
```
auth [success=4 default=ignore] pam_access.so accessfile=/etc/security/exclude-pam-weblogin.conf
auth [success=3 default=ignore] pam_succeed_if.so quiet user ingroup admin
auth [success=2 default=ignore] pam_succeed_if.so quiet uid < 70000000 
auth [success=1 default=ignore] pam_succeed_if.so quiet uid > 72999999

auth required /usr/local/lib/security/pam_weblogin.so /etc/pam-weblogin.conf
```

**Comment by FlorisFokkinga** [comment]
De documentatie moet duidelijk maken dat je als systeembeheerder moet voorkomen jezelf buiten te sluiten. ;)
