### ISSUE TITLE
"Bearer" prefix in token config optioneel maken.

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#32]
Je moet nu verplicht "Bearer abcde123" in de config file zetten.  Pas de logica aan zodat je alleen het token hoeft op te geven en dat pam_weblogin het "Bearer "-deel er automagisch bijverzint.

**Comment by mrvanes** [comment]
Ik heb er destijds juist bewust voor gekozen om de authorization header compleet configureerbaar te maken, zodat er nog ruimte is voor andere authorisatie schema's?

**Comment by baszoetekouw** [comment]
De authorization header heeft altijd een `auth-scheme` en `auth-parameters`.  Dus we kunnen dan makkelijk zat checken of `token` met `bearer ` begint en zo niet, dat er voorcatten.
