### ISSUE TITLE
PAM_TEXT_INFO messages are shown twice if they are the last conversation

### ISSUE THREAD

**Issue by mrvanes** [SURFscz/pam-weblogin#36]
Een stub voor het volgen van deze bug
https://bugzilla.mindrot.org/show_bug.cgi?id=3481

**Comment by baszoetekouw** [comment]
@mrvanes could we create a workaroud?  eg, always output an empty message?

**Comment by mrvanes** [comment]
No, I tried that and it doesn't work.

**Comment by baszoetekouw** [comment]
Could you maybe create a very minimal pam module (ie, one that only send a PAM_TEXT_INFO message) for upstream to be able to reproduce the behaviour?

**Comment by mrvanes** [comment]
https://bugzilla.mindrot.org/show_bug.cgi?id=3481#c1
