### ISSUE TITLE
Duitse aanpak uitproberen

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#37]
Onze oosterburen van DAASI gebruiken iets vergelijkbaars als pam-weblogin, maar ipv een pam-module, pluggen ze in ssh in _na_ het authenticatieproces.  Ze hebben een generieke login user, en als je daar bent ingelogt start die een management tooltje die de weblogin flow aftrapt, de goede gebruiker `adduser`t en naar de goede gebruiker `su`t. 

Zou voor ons simpel moeten zijn te implementeren.

**Comment by baszoetekouw** [comment]
We kunnen dit simpel doen als volgt:
 - gebruik een generieke access user voor _alle_ ssh sessies (sram@server.example.com)
 - in sshd_config `AuthorizedKeysCommand` configureren 
 - het `AuthorizedKeysCommand` moet een tooltje zijn die de ssh key van de gebruiker opzoekt in sram en dan als output die key geeft, met een `command=` optie die naar het authN-scriptje wijst
 - effect is dat dat de gebruiker naar binnen mag, maar dat automatisch het authn-script wordt uitgevoerd
 - heta uthn script doet het weblogin dansje, zoekt de goede usernaam op (op basis van een configureerpbaar template op basis van de oidc claims), checkt dat die gebruikr bestaat, en doet dan `su` naar die gebruiker.

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SBS/issues/366
https://github.com/SURFscz/pam-weblogin/tree/main/shell

**Comment by baszoetekouw** [comment]
Dit hoort niet echt bij de release.  Misschien moeten we nog wel een paginaatje documentatie of ene blogje ofzo schrijven met de verschillende mogeklijkheden.

**Comment by baszoetekouw** [comment]
Zie https://jira.ia.surf.nl/browse/SRAM-48
