### ISSUE TITLE
Documentation in debs and rpms

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#45]
We should add some documentation in in `/usr/share/doc/pam-weblogin/Readme` in the debs and rpms.
Maybe we can simply render the README.md to plain text and include that?

**Comment by mrvanes** [comment]
Added README.md rendering to plaintext using pandoc for DEBs building.

**Comment by mrvanes** [comment]
Added RPM README rendering and packaging

**Comment by baszoetekouw** [comment]
confirmed
