### ISSUE TITLE
Move config to /etc/security/pam-weblogin.conf

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#47]
Consider moving the config to `/etc/security/pam-weblogin.conf`
Currently in `/etc/pam-weblogin.conf`.

**Comment by baszoetekouw** [comment]
pam-weblogin should search both location, prefer the security one, and install there by defualt

**Comment by HarryKodden** [comment]
I think more important than location are the file permission flags. At this moment they are : 
```
gitpod /workspace/pam-weblogin (fix-conf-location) $ ls -l /etc/security/pam-weblogin.conf 
-rw-r--r-- 1 root root 115 Jun 14 08:52 /etc/security/pam-weblogin.conf
```

I suggest to have this changed to 600

pam-weblogin is not searching on both location, it is only reading the configuration that is explicitly reference in the **/etc/pam.d/weblogin** file

apart from that: the module works as expected.

Conclusion: Fix is accepted, will record a new issue to adjust file permissions
