### ISSUE TITLE
Show ascii-QR code of login url.

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#50]
In addition to showing the URL to login in, also show the same URL as a (ascii-)QR code.

See eg https://github.com/fumiyas/qrc

**Comment by baszoetekouw** [comment]
https://github.com/fukuchi/libqrencode

**Comment by baszoetekouw** [comment]
of deze https://github.com/ricmoo/QRCode

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/fcb0549061cc93ad1d4e3e4be4f645cac43d541c

**Comment by mrvanes** [comment]
Correct
