### ISSUE TITLE
Get rid of submodule for json-parser

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#53]
git subtree might be a more viable alternative, see https://gist.github.com/SKempin/b7857a6ff6bddb05717cc17a44091202

**Comment by mrvanes** [comment]
Hmm.... I'm not undividedly enthusiastic reading up on the mentioned issues and comments https://gist.github.com/SKempin/b7857a6ff6bddb05717cc17a44091202?permalink_comment_id=4250868#gistcomment-4250868
