### ISSUE TITLE
try and document scp and sftp usage using pam_weblogin and smartshell

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/pam-weblogin#54]

**Comment by mrvanes** [comment]
https://github.com/SURFscz/pam-weblogin/commit/8e94676481711890263c234ddf1985ed3cd967f0

**Comment by FlorisFokkinga** [comment]
- This is the topic guide, a general introduction: https://wiki.surfnet.nl/display/SRAM/PAM+web+login
- This is the how to, explaining which steps to take to perform a specific task: https://wiki.surfnet.nl/display/SRAM/Connect+a+PAM+web+login+service
What is this, exactly? https://wiki.surfnet.nl/display/SRAM/PAM+weblogin
It seems like two how-tos. One explaining how to install PAM web login and another how to use it in combination with SCP and SFTP?

**Comment by FlorisFokkinga** [comment]
It seems to me we should split this page: https://wiki.surfnet.nl/display/SRAM/PAM+weblogin
- Introduction / Ready to try are copied from the topic guide on the wiki
- Installation is copied from the readme, linked on the how to on the wiki
- SCP and SFTP can be summarized to 'this just works, but not with smart shell'

I propose to move the remarks about SCP and SFTP to the topic guide and then remove this page.
