### ISSUE TITLE
smart shell should read user shell instead of assuming bash

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#72]
This is for the user experience (i.e., many systems default to zsh these days), but this might also be a security issue, for example, to bypass a user with shell set to `/bin/false`, for example, if the user means to craft their username suitably.

**Comment by mrvanes** [comment]
This is already how it works:
https://github.com/SURFscz/pam-weblogin/blob/main/shell/weblogin.py#L58
       -i, -‐login
               Run the shell specified by the target user’s password database entry as a login shell.
