### ISSUE TITLE
Update docs and specification to current state of protocol

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/pam-weblogin#80]
The docs in docs/ are quite out of date and don;t yet describe the smartshell possibilities.  Also the json example seem out of date.

**Comment by mrvanes** [comment]
https://github.com/SURFscz/pam-weblogin/commit/2c27633017421c5c7ed3f1f55a51d648dab6c295

**Comment by baszoetekouw** [comment]
Checked.  Nog een enkele typo verbeterd, maar lijkt weer helemaal prima!
