### ISSUE TITLE
weblogin.py does not work on rhel

### ISSUE THREAD

**Issue by arcovangeest** [SURFscz/pam-weblogin#85]
/opt/pam-weblogin/shell/weblogin.py gives an error on rhel due to missing --GECOS and --disable-password options.

adduser is different on ubuntu and rhel.
useradd seems to be the same on both platforms but lacks the --disable-password option.

**Comment by mrvanes** [comment]
The idea of the Smart shell weblogin.py is that it's a suggestion of what you could do after the PAM flow. So, we are not planning to make it work on all distributions (unlike the module) but leave that excersize to the user.
There may also be many other "magic" someone might want to do before enrolling users e.g.
