### ISSUE TITLE
PAM WebLogin should provide ALL groups that User is member of

### ISSUE THREAD

**Issue by HarryKodden** [SURFscz/pam-weblogin#91]

**Comment by HarryKodden** [comment]
At this moment a succesful PAM Weblogin returns a JSON document with an array of Groups that only lists the CO's that a authenticated user is member of. For detailed authorization decisions the service would like to receive all the Groups that a user is member of. This would also be consistent with the "eduperson_entitlement' claim that the OIDC authentication delivers when scope "entitlements" is requested.

Sample current situation:

```
{
	"groups": [
		{
			"id": "fef588a9-8602-476b-9443-f7db0dbb0c80",
			"name": "Sample CO",
			"short_name": "sampleco"
		}
	],
	"info": "User 78bcc51502813d86773a833ac3e43e0378a8d84e@acc.sram.eduteams.org has authenticated successfully",
	"result": "SUCCESS",
	"username": "hkodden6"
}
```

Also for the shortname, it is requested to provide the full URN of the shortname (including shortname ORG, shortname CO and shortname GROUP)

So the following adjustments are requested:
* Add CO Groups  the user is member of
* Adjust the shortname to be a full enumerated URN of the Group.

Sample of requested result:

```
{
	"groups": [
		{
			"id": "fef588a9-8602-476b-9443-f7db0dbb0c80",
			"name": "Sample CO",
			"short_name": "sampleorg:sampleco"
		},{
			"id": "...",
			"name": "Sample Group in CO",
			"short_name": "sampleorg:sampleco:samplegrp"
		}
	],
	"info": "User 78bcc51502813d86773a833ac3e43e0378a8d84e@acc.sram.eduteams.org has authenticated successfully",
	"result": "SUCCESS",
	"username": "hkodden6"
}
```

**Comment by baszoetekouw** [comment]
works, but pam module still needs update

**Comment by baszoetekouw** [comment]
continues in #92
